name: Deployment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      image-tags:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      cluster-resource-group:
        required: true
        type: string
      cluster-namespace:
        required: true
        type: string
      chart-path:
        required: true
        type: string
      chart-override-file:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.env }}
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ inputs.cluster-resource-group }}
          cluster-name: ${{ inputs.cluster-name }}

      # Runs Helm to create manifest files
      - name: Bake deployment
        uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: ${{ inputs.chart-path }}
          overrideFiles: ${{ inputs.chart-override-file }}
          helm-version: "latest"
        id: bake

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: ${{ inputs.cluster-namespace }}
          images: |
            ${{ inputs.image-tags }}
